### ISSUE TITLE
Open the wiki for more documentation

### ISSUE THREAD

**Issue by AndreasWebdev** [torch2424/piStreamRadio#10]
I think it would be a good idea to open the wiki for more in depth information and documentation. There could be a list with "perfect configurations" for different devices like the Raspberry Pi3 or 2 or other devices with different components.

Besides that there could be a simple step-by-step tutorial for total noobs.

**Comment by torch2424** [comment]
Yes! I am a big fan of documentation. I tend to not open wikis, since I like having short and sweet docs, and not having it all over the place. But I would be open to the readme just pointing to the wiki for documentation.

If you would like, I can open the wiki, and you can feel free to contribute to it as well? 

I think if the project gets anymore complicated, I will go ahead and do that, otherwise for now I feel that it is fine.

**Comment by AndreasWebdev** [comment]
Using the README is more than suitable! I'll try to think of some improvements for that!
